### PR TITLE
Issue 2 - Magnitude details endpoint Part 2

### LINKED ISSUE #2: Magnitude details endpoint
- Accept the following params Huid / Magtype / Installation / Author
- Output in json format and output is TBD.

### PR DESCRIPTION
**Pull request by jpatton-USGS**
Addresses, I the comments added to issue two:

* Did pass to ensure coding standards followed
* Added tests to MagnitudeHandler
* Added more documentation
* Cleaned up error messages
* Made it so that _getMagnitudeMomentTensors always returns all available moment tensor solutions, with the preferred solution always being first in the array.
* Could create more tests for HydraFactory, need to talk to @jmfee-usgs about that. 

fixes #2

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
- always return an array (possibly empty) from `_getMagnitudeMomentTensors`
https://github.com/usgs/hydra-web-service/pull/29/files#diff-b19b3842437db911a260652732d848f6R352

- initialize json.geometry to null when it is created 
https://github.com/usgs/hydra-web-service/pull/29/files#diff-b19b3842437db911a260652732d848f6R519
instead of here
https://github.com/usgs/hydra-web-service/pull/29/files#diff-b19b3842437db911a260652732d848f6R306

- once preferred magnitude is found, break out of the loop
https://github.com/usgs/hydra-web-service/pull/29/files#diff-b19b3842437db911a260652732d848f6R311

- use null for undefined method, can the translation be embedded in the sql using "CASE" (and later converted to an actual lookup via join)?
https://github.com/usgs/hydra-web-service/pull/29/files#diff-b19b3842437db911a260652732d848f6R595
- same with bitmasks, can those be embedded in the sql?
https://github.com/usgs/hydra-web-service/pull/29/files#diff-b19b3842437db911a260652732d848f6R510

- error message could be built with less complexity:
https://github.com/usgs/hydra-web-service/pull/29/files#diff-8cc7a63124daa10ee909df7a1aebc0d0R63
```js
var missing;

missing = [];
if (!params.huid) {
  missing.push('huid');
}
// ...

if (missing.length > 0) {
  return Promise.reject(new Error(
      'Missing required parameter' + (missing.length > 1 : 's' : '') +
      ': ' + missing.join(', ')));
}

return _this.factory.getMagnitude(...);
```

**Comment by jpatton-USGS** [comment]
**once preferred magnitude is found, break out of the loop:**
The intent, based on the conversations at today's scrum, is to return all moment tensor solutions, because that data will be needed in following sprints, instead of just the preferred.

**Comment by jmfee-usgs** [comment]
Agreed, however that loop isn't processing or attaching moment tensors to the magnitude; just setting the geometry of the parent magnitude based on the one preferred moment tensor.

**Comment by jpatton-USGS** [comment]
Ooohhh, that loop, I'm having a little trouble figuring out what parts of the code the diff links are referring to.

**Comment by jpatton-USGS** [comment]
Will discuss / work on moving translations variables into sql Monday when I get back.

**Comment by jmfee-usgs** [comment]
`_getMagnitudeMomentTensors` can just `return result.rows.map(_this._parseMagnitudeMomentTensor);` and doesn't need to check the array length (if it starts empty, the result of the map will also be empty).

`getMagnitude` no longer needs to check if _getMagnitudeMomentTensors return value is an array (it always is).


Update `_getMagnitudeMomentTensors` to order by whether the mt is preferred, so the most preferred mt will come first in the returned array; getMagnitude could then just check if the first mt is preferred and use its information...
http://stackoverflow.com/questions/1250156/how-do-i-return-rows-with-a-specific-value-first?answertab=votes#tab-top



For the bitmask logic, oracle has a `BITAND` function:
https://docs.oracle.com/cd/B28359_01/server.111/b28286/functions014.htm

And for the reference data that is not yet in a reference table, oracle has a `CASE` statement:
http://docs.oracle.com/cd/B19306_01/server.102/b14200/expressions004.htm

**Comment by jmfee-usgs** [comment]
- when repeatedly accessing a value, create a local variable:
```
var row;
row = result.rows[0]
_this._parseMagnitude(row)
_this._getMagnitudeMomentTensors(connection, row.IDMAG)
```

- curly braces should go on the same line as the `if`:
https://github.com/usgs/hydra-web-service/pull/29/files#diff-b19b3842437db911a260652732d848f6R304

```
var mt;
...

if (momentTensor.length > 0) {
  mt = momentTensor[0];
  if (mt['preferred-solution'] === true) {
    ...
    mt['derived-longitude']
    ...
  }
}
```


- It isn't clear whether the preferred magnitude is being returned first?
https://github.com/usgs/hydra-web-service/pull/29/files#diff-b19b3842437db911a260652732d848f6R404


- Add url for each magnitude in the event endpoint, site-root relative is okay e.g. "/ws/hydra/magnitude.json?params"

**Pull request merged**
