### PR TITLE
Issue 2 - Initial magnitude endpoint implementation

### LINKED ISSUE #2: Magnitude details endpoint
- Accept the following params Huid / Magtype / Installation / Author
- Output in json format and output is TBD.

### PR DESCRIPTION
**Pull request by jpatton-USGS**
Not ready yet, mostly being put up for comments by those better at javascript.

* Based on Jeremy's pull request #21, probably should merge that one and rebase this one when the time comes
* Tests need to be written
* Still need to convert source-time function and generate ntp axis in _parseMagnitudeMomentTensor, maths are hard.
* Need to figure out how to get magnitude publishable information in _parseMagnitude, this is done in Hydra via a c library using authors and db business rules.
* Generates revised magnitude details output format proposed in usgs/hydra-web-service#3
* _getMagnitudeMomentTensor supports getting preferred moment tensor or all moment tensors (a feature not technically needed for this sprint)

* Fixes #2

### CODE REVIEW

**Comment by jpatton-USGS** [comment]
Decided to just send the tensor parameters, and let the display side compute the ntp axis

**Comment by jpatton-USGS** [comment]
Added source time conversion

**Comment by jpatton-USGS** [comment]
After a discussion with Brian, we've decided to omit the magnitude publishable information from the magnitude endpoint, since it depends on a combination of:
* Database business rules.
* Authors
* Passport
* C Library functions

This seems out of scope for the current sprint.

**Comment by jpatton-USGS** [comment]
I think this is good to merge, I still have to do tests, but what's there works.  #21 should still be merged first though.

**Comment by emartinez-usgs** [comment]
Please rebase. Also see the changes @jmfee-usgs made to the EventHandler and update as appropriate.

**Pull request merged**
